multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 73, in par_pt_iters
    namelist, decomp_method=decomp_method, chkpt=True)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_permtest.py", line 29, in permutation_testing
    perm_idx = permlist[:,k]
NameError: name 'permlist' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 110, in <module>
    decomp_vals,pt_arch_dir = run_parallel_permtests(output_basedir,n_workers)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 92, in run_parallel_permtests
    P.map(par_pt_iters,worker_spec)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
NameError: name 'permlist' is not defined
