Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_DMF.py", line 5, in <module>
    cpm(sys.argv[1],sys.argv[2])
TypeError: 'module' object is not callable
