Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_stbl.py", line 4, in <module>
    ld_st.stability_testing(sys.argv[1],sys.argv[2],listpath=sys.argv[3],decomp_method=sys.argv[4])
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py", line 24, in stability_testing
    reps = load_reps(dataset_list_name)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py", line 237, in load_reps
    reps[i] = ld_br.parse_dataset(dataset_list[i])
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_brainrep.py", line 121, in parse_dataset
    data = parse_datalist(dataname_list,datadir)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_brainrep.py", line 128, in parse_datalist
    n_feat = len(PN.parse_fname(os.path.join(datadir,dataname_list[0])))
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/parse_neurodata.py", line 16, in parse_fname
    data=parser(fname)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/parse_neurodata.py", line 36, in load_csv
    data0 = np.genfromtxt(fname,delimiter=",")
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1759, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: /scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Amplitudes/sub-100307_catrun.csv not found.
