Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_MDS.py", line 51, in <module>
    listiter_MDS(sys.argv[1],sys.argv[2],listpath = sys.argv[3])
  File "/scratch/tyoeasley/brain_representations/src_py/run_MDS.py", line 27, in listiter_MDS
    save_results(results,output_dir,namelist[i])
IndexError: list index out of range
